"""Initial migration

Revision ID: f164c61f5cbb
Revises: 
Create Date: 2025-04-14 22:19:43.606016

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f164c61f5cbb'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('size', sa.Numeric(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('available', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'size', postgresql_nulls_not_distinct=True),
    schema='orders'
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('prepared_quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['orders.items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.id'], ),
    sa.PrimaryKeyConstraint('id', 'order_id', 'item_id'),
    schema='orders'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items', schema='orders')
    op.drop_table('orders', schema='orders')
    op.drop_table('items', schema='orders')
    # ### end Alembic commands ###
